# Generated by Django 5.1.3 on 2025-03-01 05:01

import django.db.models.deletion
import tinymce.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliciesAndProceduresIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(max_length=255, null=True)),
                ('page_subtitle', wagtail.fields.RichTextField(blank=True, null=True)),
                ('intro', tinymce.models.HTMLField(blank=True, null=True)),
                ('sidebar_links', wagtail.fields.StreamField([('link_blocks', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('link_title', 0), ('url', 0), ('open_in_new_tab', 1)]], {})}, null=True)),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='banner_image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PoliciesAndProceduresSubpage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(max_length=255, null=True)),
                ('page_subtitle', wagtail.fields.RichTextField(blank=True, null=True)),
                ('intro', tinymce.models.HTMLField(blank=True, null=True)),
                ('policies_and_procedures', wagtail.fields.StreamField([('policies_and_procedures', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('Link', 'link'), ('Document', 'doc')], 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('policy', 1), ('policy_link', 2), ('procedure', 1), ('procedure_link', 2), ('display_doc_type', 3), ('open_in_new_tab', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('policy_and_procedure', 6)]], {})}, null=True)),
                ('sidebar_links', wagtail.fields.StreamField([('link_blocks', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('link_title', 0), ('url', 0), ('open_in_new_tab', 1)]], {})}, null=True)),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='banner_image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
