# Generated by Django 5.1.3 on 2025-03-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies_and_procedures', '0004_alter_policiesandproceduressubpage_policies_and_procedures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policiesandproceduresindexpage',
            name='page_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policiesandproceduressubpage',
            name='page_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
