# Generated by Django 5.1.3 on 2025-03-02 15:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies_and_procedures', '0007_alter_policiesandproceduressubpage_policies_and_procedures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policiesandproceduresindexpage',
            name='sidebar_links',
            field=wagtail.fields.StreamField([('link_blocks', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('link_title', 0), ('url', 0), ('is_active_link', 1), ('open_in_new_tab', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='policiesandproceduressubpage',
            name='sidebar_links',
            field=wagtail.fields.StreamField([('link_blocks', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('link_title', 0), ('url', 0), ('is_active_link', 1), ('open_in_new_tab', 1)]], {})}, null=True),
        ),
    ]
