# Generated by Django 5.1.3 on 2025-03-02 16:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies_and_procedures', '0008_alter_policiesandproceduresindexpage_sidebar_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policiesandproceduressubpage',
            name='policies_and_procedures',
            field=wagtail.fields.StreamField([('policies_and_procedures', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('doc', 'Document'), ('link', 'Link')], 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('policy', 1), ('policy_link', 2), ('procedure', 1), ('procedure_link', 2), ('display_doc_type', 3), ('open_in_new_tab', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('policy_and_procedure', 6)]], {})}, null=True),
        ),
    ]
