# Generated by Django 5.1.3 on 2025-03-05 05:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies_and_procedures', '0013_alter_policiesandproceduressubpage_policies_and_procedures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policiesandproceduressubpage',
            name='policies_and_procedures',
            field=wagtail.fields.StreamField([('policies_and_procedures', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('doc', 'Document'), ('link', 'Link')], 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 1), ('policy', 2), ('policy_link', 3), ('procedure', 2), ('procedure_link', 3), ('display_doc_type', 4), ('open_in_new_tab', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('policy_and_procedure', 7)]], {})}, null=True),
        ),
    ]
