# Generated by Django 5.1.3 on 2025-04-01 07:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies_and_procedures', '0025_alter_highschoolpoliciesandprocedurespage_policies_and_procedures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolpoliciesandprocedurespage',
            name='policies_and_procedures',
            field=wagtail.fields.StreamField([('policies_and_procedures', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('link', 'Link'), ('doc', 'Document')], 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('document', 1), ('url', 2), ('display_doc_type', 3), ('open_in_new_tab', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('policy_and_procedure', 6)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='policiesandproceduressubpage',
            name='policies_and_procedures',
            field=wagtail.fields.StreamField([('policies_and_procedures', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Policy', 'max_length': 255, 'null': True, 'required': False}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Procedure', 'max_length': 255, 'null': True, 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('link', 'Link'), ('doc', 'Document')], 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('policy_title', 1), ('policy', 2), ('policy_link', 3), ('open_policy_in_new_tab', 4), ('procedure_title', 5), ('procedure', 2), ('procedure_link', 3), ('open_procedure_in_new_tab', 4), ('display_doc_type', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('policy_and_procedure', 8)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='policyandprocedurepage',
            name='policies_and_procedures',
            field=wagtail.fields.StreamField([('policies_and_procedures', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'null': True, 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'null': True, 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('link', 'Link'), ('doc', 'Document')], 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('document', 1), ('url', 2), ('display_doc_type', 3), ('open_in_new_tab', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('policy_list', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('policy_block', 8)]], {})}, null=True),
        ),
    ]
