# Generated by Django 5.1.3 on 2025-04-03 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies_and_procedures', '0026_alter_highschoolpoliciesandprocedurespage_policies_and_procedures_and_more'),
        ('sidebars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschoolpoliciesandprocedurespage',
            name='sidebar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sidebars.sidebar', verbose_name='sidebar'),
        ),
        migrations.AddField(
            model_name='highschoolpoliciesandprocedurespage',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar', 'Sidebar'), ('sidebar_links', 'Sidebar Links')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='policiesandproceduressubpage',
            name='sidebar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sidebars.sidebar', verbose_name='sidebar'),
        ),
        migrations.AddField(
            model_name='policiesandproceduressubpage',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar', 'Sidebar'), ('sidebar_links', 'Sidebar Links')], default='sidebar_links', max_length=255, null=True),
        ),
    ]
