# Generated by Django 5.1.3 on 2025-08-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies_and_procedures', '0038_alter_highschoolpoliciesandprocedurespage_sidebar_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolpoliciesandprocedurespage',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar', 'Sidebar'), ('sidebar_links', 'Sidebar Links')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policiesandproceduressubpage',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar', 'Sidebar'), ('sidebar_links', 'Sidebar Links')], default='sidebar_links', max_length=255, null=True),
        ),
    ]
