# Generated by Django 5.1.3 on 2025-01-16 18:07

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FeePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(max_length=255, null=True)),
                ('elicos_fee_block', wagtail.fields.StreamField([('elicos_fee_block', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.StructBlock', [[('porgram', 0), ('cricos', 0), ('tution_fee', 0)]], {})}, null=True)),
                ('high_school_fee_block', wagtail.fields.StreamField([('high_school_fee_block', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.StructBlock', [[('porgram', 0), ('cricos', 0), ('tution_fee', 0)]], {})}, null=True)),
                ('higher_education_fee_block', wagtail.fields.StreamField([('higher_education_fee_block', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.StructBlock', [[('porgram', 0), ('cricos', 0), ('course_duration', 0), ('offshore_tution_fee', 0), ('onshore_fee_help', 0)]], {})}, null=True)),
            ],
            options={
                'verbose_name': 'Fee Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
