# Generated by Django 5.1.3 on 2025-01-16 18:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_feepage_higher_education_fee_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepage',
            name='higher_education_fee_block',
            field=wagtail.fields.StreamField([('higher_education_fee_block', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.StructBlock', [[('porgram', 0), ('cricos', 0), ('course_duration', 0), ('offshore_tution_fee', 0), ('onshore_tuition_fee', 0), ('domestic_fee_help', 0)]], {})}, null=True),
        ),
    ]
