# Generated by Django 5.1.3 on 2025-01-16 19:04

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_alter_feepage_higher_education_fee_block'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(max_length=255, null=True)),
                ('elicos_intake_block', wagtail.fields.StreamField([('elicos_intake_block', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.StructBlock', [[('program', 0), ('intake', 0)]], {})}, null=True)),
                ('high_school_intake_block', wagtail.fields.StreamField([('high_school_intake_block', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('program', 0), ('current_intake', 0), ('next_intake', 0), ('year_10', 1), ('vce_year_11', 1), ('vce_year_12', 1)]], {})}, null=True)),
                ('higher_education_intake_block', wagtail.fields.StreamField([('higher_education_intake_block', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.StructBlock', [[('program', 0), ('current_intake', 0), ('next_intake', 0)]], {})}, null=True)),
            ],
            options={
                'verbose_name': 'Intake Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='feepage',
            name='elicos_fee_block',
            field=wagtail.fields.StreamField([('elicos_fee_block', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.StructBlock', [[('program', 0), ('cricos', 0), ('tution_fee', 0)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='feepage',
            name='high_school_fee_block',
            field=wagtail.fields.StreamField([('high_school_fee_block', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.StructBlock', [[('program', 0), ('cricos', 0), ('tution_fee', 0)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='feepage',
            name='higher_education_fee_block',
            field=wagtail.fields.StreamField([('higher_education_fee_block', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.StructBlock', [[('program', 0), ('cricos', 0), ('course_duration', 0), ('offshore_tution_fee', 0), ('onshore_tuition_fee', 0), ('domestic_fee_help', 0)]], {})}, null=True),
        ),
    ]
