# Generated by Django 5.1.3 on 2025-01-21 12:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_intakepage_higher_education_intakes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakepage',
            name='higher_education_intakes',
            field=wagtail.fields.StreamField([('table_row', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.StructBlock', [[('description', 0)]], {}), 2: ('wagtail.blocks.ListBlock', (1,), {}), 3: ('wagtail.blocks.StructBlock', [[('title', 2)]], {})}, null=True),
        ),
    ]
