# Generated by Django 5.1.3 on 2025-01-21 12:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_alter_intakepage_higher_education_intakes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakepage',
            name='higher_education_intakes',
            field=wagtail.fields.StreamField([('higher_education_intakes', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('description', 0), ('is_title', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {}), 4: ('wagtail.blocks.StructBlock', [[('title', 3)]], {})}, null=True),
        ),
    ]
