# Generated by Django 5.1.3 on 2025-01-24 03:39

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_intakepage_banner_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='banner_image'),
        ),
        migrations.AddField(
            model_name='feepage',
            name='page_intro',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakepage',
            name='page_intro',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
