# Generated by Django 5.1.3 on 2025-01-27 11:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_feepage_banner_image_feepage_page_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepage',
            name='domestic_higher_education_fee_block',
            field=wagtail.fields.StreamField([('domestic_higher_education_fee_block', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False, 'verbose_name': 'Upload Fee File'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('fee', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='feepage',
            name='higher_education_fee_block',
            field=wagtail.fields.StreamField([('higher_education_fee_block', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'null': True, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('program', 0), ('cricos', 0), ('course_duration', 0), ('international_tution_fee', 1), ('domestic_tuition_fee', 1), ('domestic_fee_help', 1)]], {})}, null=True),
        ),
    ]
