# Generated by Django 5.1.3 on 2025-01-27 11:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0013_feepage_domestic_higher_education_fee_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepage',
            name='domestic_higher_education_fee_block',
            field=wagtail.fields.StreamField([('domestic_higher_education_fee_block', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False, 'verbose_name': 'Upload Fee File'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('fee', 1)]], {})}, null=True),
        ),
    ]
