# Generated by Django 5.1.3 on 2025-01-27 17:53

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0014_alter_feepage_domestic_higher_education_fee_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepage',
            name='elicos_course_fee',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepage',
            name='elicos_other_fee',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepage',
            name='high_school_course_fee',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepage',
            name='high_school_other_fee',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepage',
            name='higher_education_course_fee',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepage',
            name='higher_education_other_fee',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
