# Generated by Django 5.1.3 on 2025-01-27 18:06

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0015_feepage_elicos_course_fee_feepage_elicos_other_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feepage',
            old_name='elicos_course_fee',
            new_name='domestic_elicos_course_fee',
        ),
        migrations.RenameField(
            model_name='feepage',
            old_name='elicos_other_fee',
            new_name='domestic_elicos_other_fee',
        ),
        migrations.RenameField(
            model_name='feepage',
            old_name='high_school_course_fee',
            new_name='domestic_high_school_course_fee',
        ),
        migrations.RenameField(
            model_name='feepage',
            old_name='high_school_other_fee',
            new_name='domestic_high_school_other_fee',
        ),
        migrations.RenameField(
            model_name='feepage',
            old_name='higher_education_course_fee',
            new_name='domestic_higher_education_course_fee',
        ),
        migrations.RenameField(
            model_name='feepage',
            old_name='higher_education_other_fee',
            new_name='domestic_higher_education_other_fee',
        ),
        migrations.AddField(
            model_name='feepage',
            name='international_elicos_course_fee',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepage',
            name='international_elicos_other_fee',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepage',
            name='international_high_school_course_fee',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepage',
            name='international_high_school_other_fee',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepage',
            name='international_higher_education_course_fee',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepage',
            name='international_higher_education_other_fee',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
