# Generated by Django 5.1.3 on 2025-01-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0016_rename_elicos_course_fee_feepage_domestic_elicos_course_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepage',
            name='domestic_higher_education_fee_block',
        ),
        migrations.RemoveField(
            model_name='feepage',
            name='elicos_fee_block',
        ),
        migrations.RemoveField(
            model_name='feepage',
            name='high_school_fee_block',
        ),
        migrations.RemoveField(
            model_name='feepage',
            name='higher_education_fee_block',
        ),
    ]
