# Generated by Django 5.1.3 on 2025-01-27 19:20

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0017_remove_feepage_domestic_higher_education_fee_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepage',
            name='fee_help',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepage',
            name='payment_due_dates',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepage',
            name='payment_methods',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
