# Generated by Django 5.1.3 on 2025-01-27 20:31

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0021_alter_feepage_fee_help_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepage',
            name='payment_due_dates',
        ),
        migrations.AddField(
            model_name='feepage',
            name='elicos_payment_due_dates',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepage',
            name='high_school_payment_due_dates',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepage',
            name='higher_education_payment_due_dates',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
