# Generated by Django 5.1.3 on 2025-03-02 16:41

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0023_admissionindex_banner_image_admissionindex_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionindex',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
