# Generated by Django 5.1.3 on 2024-12-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
