# Generated by Django 5.1.3 on 2025-01-29 04:48

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
