# Generated by Django 5.1.3 on 2025-02-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogindex_featured_image_blogindex_sub_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindex',
            name='svg_icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsindexpage',
            name='svg_icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='svg_icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
