# Generated by Django 5.1.3 on 2025-02-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogindex_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='event_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
