# Generated by Django 5.1.3 on 2025-02-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_eventpage_event_time_alter_eventpage_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
