# Generated by Django 5.1.3 on 2025-08-13 07:27

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_eventpage_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='event_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event End Date'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event Start Date'),
        ),
    ]
