# Generated by Django 5.1.3 on 2025-08-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_eventpage_event_end_date_alter_eventpage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='event_end_time',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Event End Time'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='event_time',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Event Start Time'),
        ),
    ]
