# Generated by Django 5.1.3 on 2025-09-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_eventpage_event_end_time_alter_eventpage_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='featured_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
