# Generated by Django 5.1.3 on 2024-12-27 07:06

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('course_title', models.CharField(blank=True, max_length=255, null=True)),
                ('study_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('course_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('course_location', models.CharField(blank=True, max_length=255, null=True)),
                ('cricos_code', models.CharField(blank=True, max_length=10, null=True)),
                ('course_intro', wagtail.fields.RichTextField(blank=True, null=True)),
                ('course_requirement', wagtail.fields.RichTextField(blank=True, null=True)),
                ('academic_requirement', wagtail.fields.RichTextField(blank=True, null=True)),
                ('english_requirement', wagtail.fields.RichTextField(blank=True, null=True)),
                ('age_requirement', wagtail.fields.RichTextField(blank=True, null=True)),
                ('career_outcome', wagtail.fields.RichTextField(blank=True, null=True)),
                ('course_overview', wagtail.fields.RichTextField(blank=True, null=True)),
                ('core_units', wagtail.fields.RichTextField(blank=True, null=True)),
                ('elective_units', wagtail.fields.RichTextField(blank=True, null=True)),
                ('assessment_methods', wagtail.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Course Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CoursesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Courses Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DegreeIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
