# Generated by Django 5.1.3 on 2024-12-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursepage_accreditation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesindexpage',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='degreeindexpage',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
