# Generated by Django 5.1.3 on 2024-12-27 12:01

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursesindexpage_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='degreeindexpage',
            name='page_description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
