# Generated by Django 5.1.3 on 2024-12-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursepage_is_popular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='intakes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
