# Generated by Django 5.1.3 on 2024-12-28 12:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_coursepage_intakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesindexpage',
            name='page_description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
