# Generated by Django 5.1.3 on 2024-12-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursesindexpage_page_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='course_type',
            field=models.CharField(choices=[('HE', 'Higher Education'), ('HS', 'High School'), ('EL', 'English Language')], default='HE', max_length=2),
        ),
    ]
