# Generated by Django 5.1.3 on 2024-12-28 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_coursepage_course_type'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoursePage',
            new_name='HigherEducationCoursePage',
        ),
    ]
