# Generated by Django 5.1.3 on 2024-12-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_rename_coursepage_highereducationcoursepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highereducationcoursepage',
            options={'verbose_name': 'Higher Education Course Page'},
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='course_type',
            field=models.CharField(choices=[('PG', 'Postgraduate'), ('UG', 'Undergraduate')], default='UG', max_length=2),
        ),
    ]
