# Generated by Django 5.1.3 on 2024-12-28 13:19

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_highereducationcoursepage_options_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighSchoolCoursePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('is_popular', models.BooleanField(default=False)),
                ('course_title', models.CharField(blank=True, max_length=255, null=True)),
                ('cricos_code', models.CharField(blank=True, max_length=10, null=True)),
                ('course_detail', wagtail.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'High School Course Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
