# Generated by Django 5.1.3 on 2024-12-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_highereducationcoursepage_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='course_header_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
