# Generated by Django 5.1.3 on 2024-12-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_highereducationcoursepage_course_header_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='course_type',
            field=models.CharField(choices=[('PG', 'Postgraduate'), ('UG', 'Undergraduate'), ('DIP', 'Diploma'), ('VET', 'VET')], default='UG', max_length=3),
        ),
    ]
