# Generated by Django 5.1.3 on 2024-12-29 04:54

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_highereducationcoursepage_course_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highereducationcoursepage',
            old_name='academic_requirement',
            new_name='academic_requirement_domestic',
        ),
        migrations.RenameField(
            model_name='highereducationcoursepage',
            old_name='english_requirement',
            new_name='academic_requirement_international',
        ),
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='aqf_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='english_requirement_domestic',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='english_requirement_international',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='fee_domestic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='fee_international',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
