# Generated by Django 5.1.3 on 2024-12-29 05:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_rename_academic_requirement_highereducationcoursepage_academic_requirement_domestic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highereducationcoursepage',
            old_name='core_units',
            new_name='course_structure',
        ),
        migrations.RemoveField(
            model_name='highereducationcoursepage',
            name='elective_units',
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='course_duration',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='course_header_description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='course_location',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='fee_domestic',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='fee_international',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='intakes',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='study_mode',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
