# Generated by Django 5.1.3 on 2024-12-29 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_rename_core_units_highereducationcoursepage_course_structure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highereducationcoursepage',
            old_name='career_outcome',
            new_name='career_outcomes',
        ),
        migrations.RenameField(
            model_name='highereducationcoursepage',
            old_name='course_structure',
            new_name='course_units',
        ),
    ]
