# Generated by Django 5.1.3 on 2024-12-29 08:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_rename_career_outcome_highereducationcoursepage_career_outcomes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='ielts',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
