# Generated by Django 5.1.3 on 2024-12-29 12:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_highereducationcoursepage_ielts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highereducationcoursepage',
            name='course_intro',
        ),
        migrations.RemoveField(
            model_name='highereducationcoursepage',
            name='course_units',
        ),
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='core_units',
            field=wagtail.fields.StreamField([('core_units', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'blank': False, 'null': True}), 2: ('wagtail.blocks.StructBlock', [[('unit_title', 0), ('unit_description', 1)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='ellective_units',
            field=wagtail.fields.StreamField([('ellective_units', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'blank': False, 'null': True}), 2: ('wagtail.blocks.StructBlock', [[('unit_title', 0), ('unit_description', 1)]], {})}, null=True),
        ),
    ]
