# Generated by Django 5.1.3 on 2024-12-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_highereducationcoursepage_brochure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highereducationcoursepage',
            old_name='brochure',
            new_name='course_brochure',
        ),
    ]
