# Generated by Django 5.1.3 on 2025-01-14 05:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_rename_brochure_highereducationcoursepage_course_brochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='core_units_block',
            field=wagtail.fields.RichTextField(blank=True, help_text="Use this block when you only want to add title of units. This is helpful when you don't want to display accordions for unit title and description.", null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='core_units',
            field=wagtail.fields.StreamField([('core_units', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'null': True}), 2: ('wagtail.blocks.StructBlock', [[('unit_title', 0), ('unit_description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='ellective_units',
            field=wagtail.fields.StreamField([('ellective_units', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'null': True}), 2: ('wagtail.blocks.StructBlock', [[('unit_title', 0), ('unit_description', 1)]], {})}, null=True),
        ),
    ]
