# Generated by Django 5.1.3 on 2025-01-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_highereducationcoursepage_core_units_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='course_type',
            field=models.CharField(choices=[('PG', 'Postgraduate'), ('UG', 'Undergraduate')], default='UG', max_length=3),
        ),
    ]
