# Generated by Django 5.1.3 on 2025-01-14 11:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_highereducationcoursepage_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='accounting_specialisation_units',
            field=wagtail.fields.StreamField([('accounting_specialisation_units', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'null': True}), 2: ('wagtail.blocks.StructBlock', [[('unit_title', 0), ('unit_description', 1)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='management_specialisation_units',
            field=wagtail.fields.StreamField([('management_specialisation_units', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'null': True}), 2: ('wagtail.blocks.StructBlock', [[('unit_title', 0), ('unit_description', 1)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='marketing_specialisation_units',
            field=wagtail.fields.StreamField([('marketing_specialisation_units', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'null': True}), 2: ('wagtail.blocks.StructBlock', [[('unit_title', 0), ('unit_description', 1)]], {})}, null=True),
        ),
    ]
