# Generated by Django 5.1.3 on 2025-01-14 12:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_highereducationcoursepage_accounting_specialisation_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='core_units',
            field=wagtail.fields.StreamField([('heading', 0), ('core_units', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'null': True}), 3: ('wagtail.blocks.StructBlock', [[('unit_title', 1), ('unit_description', 2)]], {})}, null=True),
        ),
    ]
