# Generated by Django 5.1.3 on 2025-01-14 12:32

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_highereducationcoursepage_core_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='accounting_specialisation_units_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='core_units_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='ellective_units_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='management_specialisation_units_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='marketing_specialisation_units_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='core_units',
            field=wagtail.fields.StreamField([('core_units', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'null': True}), 2: ('wagtail.blocks.StructBlock', [[('unit_title', 0), ('unit_description', 1)]], {})}, null=True),
        ),
    ]
