# Generated by Django 5.1.3 on 2025-01-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_highereducationcoursepage_accounting_specialisation_units_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='course_type',
            field=models.CharField(choices=[('PG', 'Postgraduate'), ('UG', 'Undergraduate'), ('DIP', 'Diploma')], default='UG', max_length=3),
        ),
    ]
