# Generated by Django 5.1.3 on 2025-01-14 16:33

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_highereducationcoursepage_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='pathways',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='student_workload',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
