# Generated by Django 5.1.3 on 2025-01-14 17:37

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_highereducationcoursepage_pathways_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highschoolcoursepage',
            name='course_detail',
        ),
        migrations.AddField(
            model_name='highschoolcoursepage',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
