# Generated by Django 5.1.3 on 2025-01-14 17:53

import django.db.models.deletion
import tinymce.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_remove_highschoolcoursepage_course_detail_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='highschoolcoursepage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image'),
        ),
        migrations.AddField(
            model_name='highschoolcoursepage',
            name='course_brochure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='highschoolcoursepage',
            name='course_header_description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ElicosCoursePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('is_popular', models.BooleanField(default=False)),
                ('course_title', models.CharField(blank=True, max_length=255, null=True)),
                ('cricos_code', models.CharField(blank=True, max_length=10, null=True)),
                ('course_header_description', wagtail.fields.RichTextField(blank=True, null=True)),
                ('course_duration', wagtail.fields.RichTextField(blank=True, null=True)),
                ('class_hours', wagtail.fields.RichTextField(blank=True, null=True)),
                ('location', wagtail.fields.RichTextField(blank=True, null=True)),
                ('average_class_size', wagtail.fields.RichTextField(blank=True, null=True)),
                ('level_available', wagtail.fields.RichTextField(blank=True, null=True)),
                ('entry_requirements', wagtail.fields.RichTextField(blank=True, null=True)),
                ('intakes', wagtail.fields.RichTextField(blank=True, null=True)),
                ('fees', wagtail.fields.RichTextField(blank=True, null=True)),
                ('course_overview', wagtail.fields.RichTextField(blank=True, null=True)),
                ('learning_outcome', tinymce.models.HTMLField(blank=True, null=True)),
                ('assessment', wagtail.fields.RichTextField(blank=True, null=True)),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image')),
                ('course_brochure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.document')),
            ],
            options={
                'verbose_name': 'Elicos Course Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
