# Generated by Django 5.1.3 on 2025-01-20 12:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_highschoolcoursepage_banner_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highereducationcoursepage',
            name='age_requirement',
        ),
        migrations.RemoveField(
            model_name='highereducationcoursepage',
            name='course_requirement',
        ),
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='age_requirement_domestic',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='age_requirement_international',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='course_requirement_domestic',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='course_requirement_international',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='academic_requirement_domestic',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='academic_requirement_international',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='assessment_methods',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='career_outcomes',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='core_units_block',
            field=tinymce.models.HTMLField(blank=True, help_text="Use this block when you only want to add title of units. This is helpful when you don't want to display accordions for unit title and description.", null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='course_overview',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='english_requirement_domestic',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='english_requirement_international',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
