# Generated by Django 5.1.3 on 2025-01-20 12:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_remove_highereducationcoursepage_age_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='course_units',
            field=wagtail.fields.StreamField([('course_units', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'null': True}), 3: ('wagtail.blocks.StructBlock', [[('unit_title', 1), ('unit_description', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('units', 4)]], {})}, null=True),
        ),
    ]
