# Generated by Django 5.1.3 on 2025-01-20 12:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_highereducationcoursepage_course_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='course_units',
            field=wagtail.fields.StreamField([('course_units', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'blank': True, 'max_length': 255, 'null': True}), 2: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 3: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'null': True}), 4: ('wagtail.blocks.StructBlock', [[('unit_title', 2), ('unit_description', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('sub_title', 1), ('units', 5)]], {})}, null=True),
        ),
    ]
