# Generated by Django 5.1.3 on 2025-01-20 12:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_alter_highereducationcoursepage_course_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='accounting_specialisation_units',
            field=wagtail.fields.StreamField([('accounting_specialisation_units', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'null': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'null': True, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('unit_title', 0), ('unit_description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='core_units',
            field=wagtail.fields.StreamField([('core_units', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'null': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'null': True, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('unit_title', 0), ('unit_description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='course_units',
            field=wagtail.fields.StreamField([('course_units', 7)], blank=True, block_lookup={0: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'If false, only course title will be displayed as lists'}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'null': True, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'null': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'null': True, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('unit_title', 3), ('unit_description', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('display_as_dropdown', 0), ('title', 1), ('sub_title', 2), ('units', 6)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='ellective_units',
            field=wagtail.fields.StreamField([('ellective_units', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'null': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'null': True, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('unit_title', 0), ('unit_description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='management_specialisation_units',
            field=wagtail.fields.StreamField([('management_specialisation_units', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'null': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'null': True, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('unit_title', 0), ('unit_description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='marketing_specialisation_units',
            field=wagtail.fields.StreamField([('marketing_specialisation_units', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'null': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'null': True, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('unit_title', 0), ('unit_description', 1)]], {})}, null=True),
        ),
    ]
