# Generated by Django 5.1.3 on 2025-01-24 04:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_alter_highereducationcoursepage_accounting_specialisation_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='ielts_domestic',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highereducationcoursepage',
            name='ielts_international',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
