# Generated by Django 5.1.3 on 2025-01-24 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_highereducationcoursepage_ielts_domestic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highereducationcoursepage',
            name='ielts',
        ),
    ]
