# Generated by Django 5.1.3 on 2025-01-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_alter_highereducationcoursepage_course_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeindexpage',
            name='degree_type',
            field=models.CharField(choices=[('HE', 'Higher Education'), ('HS', 'High School'), ('EL', 'Elicos')], default='HE', max_length=3),
        ),
    ]
