# Generated by Django 5.1.3 on 2026-03-15 14:46

import django.db.models.deletion
import tinymce.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_degreeindexpage_degree_type'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highereducationcoursepage',
            name='accounting_specialisation_units',
        ),
        migrations.RemoveField(
            model_name='highereducationcoursepage',
            name='accounting_specialisation_units_title',
        ),
        migrations.RemoveField(
            model_name='highereducationcoursepage',
            name='ellective_units',
        ),
        migrations.RemoveField(
            model_name='highereducationcoursepage',
            name='ellective_units_title',
        ),
        migrations.RemoveField(
            model_name='highereducationcoursepage',
            name='management_specialisation_units',
        ),
        migrations.RemoveField(
            model_name='highereducationcoursepage',
            name='management_specialisation_units_title',
        ),
        migrations.RemoveField(
            model_name='highereducationcoursepage',
            name='marketing_specialisation_units',
        ),
        migrations.RemoveField(
            model_name='highereducationcoursepage',
            name='marketing_specialisation_units_title',
        ),
        migrations.AddField(
            model_name='degreeindexpage',
            name='about_content',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='degreeindexpage',
            name='about_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='About Image'),
        ),
        migrations.AddField(
            model_name='degreeindexpage',
            name='about_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='highereducationcoursepage',
            name='core_units_block',
            field=tinymce.models.HTMLField(blank=True, help_text='Use when only unit titles are needed', null=True),
        ),
    ]
