# Generated by Django 5.1.3 on 2026-03-15 15:44

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_remove_highereducationcoursepage_accounting_specialisation_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeindexpage',
            name='elicos_team',
            field=wagtail.fields.StreamField([('department', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('position', 1), ('qualification', 2), ('description', 2), ('profile_image', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('department_title', 0), ('team_members', 5)]], {})}),
        ),
        migrations.AddField(
            model_name='degreeindexpage',
            name='ready_links',
            field=wagtail.fields.StreamField([('link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.URLBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('url', 1)]], {})}),
        ),
        migrations.AddField(
            model_name='degreeindexpage',
            name='ready_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='degreeindexpage',
            name='team_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
