# Generated by Django 5.1.3 on 2024-12-05 10:46

import django.db.models.deletion
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_carousel',
            field=wagtail.fields.StreamField([('banner_carousel', 7)], blank=True, block_lookup={0: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'blank': True, 'null': True}), 2: ('wagtail.blocks.CharBlock', (), {'blank': True, 'default': '#FFFFFF', 'max_length': 50, 'null': True, 'verbose_name': 'Text Color'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'blank': True, 'null': True, 'on_delete': django.db.models.deletion.SET_NULL, 'related_name': '+', 'verbose_name': 'Background Image'}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full Width'), ('fit', 'Fit')]}), 5: ('wagtail.blocks.CharBlock', (), {'blank': True, 'default': '#FFFFFF', 'max_length': 50, 'null': True, 'verbose_name': 'Background Color'}), 6: ('wagtail.blocks.CharBlock', (), {'blank': True, 'default': 'btn-primary', 'help_text': 'Button class for learn more button. available classes are [btn-parimary (blue), btn-danger (red), btn-success (green), btn-warning (yellow), btn-info (light blue), btn-default (grey)]', 'max_length': 50, 'null': True, 'verbose_name': 'Button Class'}), 7: ('wagtail.blocks.StructBlock', [[('active', 0), ('heading', 1), ('heading_text_color', 2), ('description', 1), ('description_text_color', 2), ('background_image', 3), ('image_width', 4), ('bg_color', 5), ('btn_title', 1), ('btn_link', 1), ('btn_class', 6)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
