# Generated by Django 5.1.3 on 2024-12-11 10:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_body_homepage_about_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='important_urls',
            field=wagtail.fields.StreamField([('important_urls', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.URLBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('url', 1)]], {})}, null=True),
        ),
    ]
