# Generated by Django 5.1.3 on 2024-12-11 10:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_important_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='important_urls',
            field=wagtail.fields.StreamField([('important_urls', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.URLBlock', (), {}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('url', 1), ('open_in_new_tab', 2)]], {})}, null=True),
        ),
    ]
