# Generated by Django 5.1.3 on 2024-12-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_indexpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexPage',
        ),
    ]
