# Generated by Django 5.1.3 on 2025-01-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_htmlpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='htmlpage',
            name='page_title',
        ),
    ]
