# Generated by Django 5.1.3 on 2025-01-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_linkpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpage',
            name='open_in_new_tab',
            field=models.BooleanField(default=False),
        ),
    ]
