# Generated by Django 5.1.3 on 2025-01-16 15:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_linkpage_open_in_new_tab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkpage',
            name='open_in_new_tab',
        ),
        migrations.AlterField(
            model_name='linkpage',
            name='link_block',
            field=wagtail.fields.StreamField([('link_blocks', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('link_title', 0), ('url', 0), ('open_in_new_tab', 1)]], {})}, null=True),
        ),
    ]
