# Generated by Django 5.1.3 on 2025-03-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_linkpage_link_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlpage',
            name='page_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
