# Generated by Django 5.1.3 on 2025-03-05 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_linkpagesidebar'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpagesidebar',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='banner_image'),
        ),
        migrations.AddField(
            model_name='linkpagesidebar',
            name='page_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linkpagesidebar',
            name='page_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
