# Generated by Django 5.1.3 on 2025-03-05 05:59

import django.db.models.deletion
import tinymce.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_linkpagesidebar_banner_image_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPageSidebar',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(max_length=255, null=True)),
                ('page_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('page_intro', tinymce.models.HTMLField(blank=True, null=True)),
                ('document_block', wagtail.fields.StreamField([('document_block', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('link', 'Link'), ('doc', 'Document')], 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('document', 1), ('link', 2), ('display_doc_type', 3), ('open_in_new_tab', 4)]], {})}, null=True)),
                ('sidebar_links', wagtail.fields.StreamField([('link_blocks', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('link_title', 0), ('url', 0), ('is_active_link', 1), ('open_in_new_tab', 1)]], {})}, null=True)),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='banner_image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
