# Generated by Django 5.1.3 on 2025-04-01 07:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_sidebarhtmlpage_page_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordionhtmlpage',
            name='sidebar_links',
            field=wagtail.fields.StreamField([('link_blocks', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 500, 'null': True}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('link_title', 0), ('url', 1), ('is_active_link', 2), ('open_in_new_tab', 2)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='documentpagesidebar',
            name='sidebar_links',
            field=wagtail.fields.StreamField([('link_blocks', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 500, 'null': True}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('link_title', 0), ('url', 1), ('is_active_link', 2), ('open_in_new_tab', 2)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='linkpage',
            name='link_block',
            field=wagtail.fields.StreamField([('link_blocks', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 500, 'null': True}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('link_title', 0), ('url', 1), ('is_active_link', 2), ('open_in_new_tab', 2)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='linkpagesidebar',
            name='link_block',
            field=wagtail.fields.StreamField([('link_blocks', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 500, 'null': True}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('link_title', 0), ('url', 1), ('is_active_link', 2), ('open_in_new_tab', 2)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='linkpagesidebar',
            name='sidebar_links',
            field=wagtail.fields.StreamField([('link_blocks', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 500, 'null': True}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('link_title', 0), ('url', 1), ('is_active_link', 2), ('open_in_new_tab', 2)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='sidebarhtmlpage',
            name='sidebar_links',
            field=wagtail.fields.StreamField([('link_blocks', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 500, 'null': True}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('link_title', 0), ('url', 1), ('is_active_link', 2), ('open_in_new_tab', 2)]], {})}, null=True),
        ),
    ]
