# Generated by Django 5.1.3 on 2025-04-01 07:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_accordionhtmlpage_sidebar_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordionhtmlpage',
            name='sidebar_links',
            field=wagtail.fields.StreamField([('link_blocks', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('link_title', 0), ('url', 0), ('is_active_link', 1), ('open_in_new_tab', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='documentpagesidebar',
            name='document_block',
            field=wagtail.fields.StreamField([('document_block', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('link', 'Link'), ('doc', 'Document')], 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('document', 1), ('link', 2), ('display_doc_type', 3), ('open_in_new_tab', 4)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='documentpagesidebar',
            name='sidebar_links',
            field=wagtail.fields.StreamField([('link_blocks', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('link_title', 0), ('url', 0), ('is_active_link', 1), ('open_in_new_tab', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='linkpage',
            name='link_block',
            field=wagtail.fields.StreamField([('link_blocks', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('link_title', 0), ('url', 0), ('is_active_link', 1), ('open_in_new_tab', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='linkpagesidebar',
            name='link_block',
            field=wagtail.fields.StreamField([('link_blocks', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('link_title', 0), ('url', 0), ('is_active_link', 1), ('open_in_new_tab', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='linkpagesidebar',
            name='sidebar_links',
            field=wagtail.fields.StreamField([('link_blocks', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('link_title', 0), ('url', 0), ('is_active_link', 1), ('open_in_new_tab', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='sidebarhtmlpage',
            name='sidebar_links',
            field=wagtail.fields.StreamField([('link_blocks', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('link_title', 0), ('url', 0), ('is_active_link', 1), ('open_in_new_tab', 1)]], {})}, null=True),
        ),
    ]
