# Generated by Django 5.1.3 on 2025-04-01 07:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_documentpagesidebar_document_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpagesidebar',
            name='document_block',
            field=wagtail.fields.StreamField([('document_block', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('link', 'Link'), ('doc', 'Document')], 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('document', 1), ('link', 2), ('display_doc_type', 3), ('open_in_new_tab', 4)]], {})}, null=True),
        ),
    ]
