# Generated by Django 5.1.3 on 2025-04-01 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_documentpagesidebar_document_block'),
        ('sidebars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpagesidebar',
            name='sidebar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sidebars.sidebar', verbose_name='sidebar'),
        ),
        migrations.AddField(
            model_name='sidebarhtmlpage',
            name='sidebar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sidebars.sidebar', verbose_name='sidebar'),
        ),
    ]
