# Generated by Django 5.1.3 on 2025-04-03 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_linkpagesidebar_sidebar_sidebarhtmlpage_sidebar'),
        ('sidebars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accordionhtmlpage',
            name='sidebar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sidebars.sidebar', verbose_name='sidebar'),
        ),
        migrations.AddField(
            model_name='accordionhtmlpage',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar_links', 'Sidebar Links'), ('sidebar', 'Sidebar')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentpagesidebar',
            name='sidebar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sidebars.sidebar', verbose_name='sidebar'),
        ),
        migrations.AddField(
            model_name='documentpagesidebar',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar_links', 'Sidebar Links'), ('sidebar', 'Sidebar')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linkpagesidebar',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar_links', 'Sidebar Links'), ('sidebar', 'Sidebar')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sidebarhtmlpage',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar_links', 'Sidebar Links'), ('sidebar', 'Sidebar')], default='sidebar_links', max_length=255, null=True),
        ),
    ]
