# Generated by Django 5.1.3 on 2025-05-15 12:35

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_accordionhtmlpage_sidebar_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkpage',
            name='page_description',
        ),
        migrations.AddField(
            model_name='linkpage',
            name='page_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linkpage',
            name='page_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accordionhtmlpage',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar_links', 'Sidebar Links'), ('sidebar', 'Sidebar')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentpagesidebar',
            name='document_block',
            field=wagtail.fields.StreamField([('document_block', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('doc', 'Document'), ('link', 'Link')], 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('document', 1), ('link', 2), ('display_doc_type', 3), ('open_in_new_tab', 4)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='documentpagesidebar',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar_links', 'Sidebar Links'), ('sidebar', 'Sidebar')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='linkpagesidebar',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar_links', 'Sidebar Links'), ('sidebar', 'Sidebar')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sidebarhtmlpage',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar_links', 'Sidebar Links'), ('sidebar', 'Sidebar')], default='sidebar_links', max_length=255, null=True),
        ),
    ]
