# Generated by Django 5.1.3 on 2025-05-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_remove_linkpage_page_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordionhtmlpage',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar', 'Sidebar'), ('sidebar_links', 'Sidebar Links')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentpagesidebar',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar', 'Sidebar'), ('sidebar_links', 'Sidebar Links')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='linkpagesidebar',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar', 'Sidebar'), ('sidebar_links', 'Sidebar Links')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sidebarhtmlpage',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar', 'Sidebar'), ('sidebar_links', 'Sidebar Links')], default='sidebar_links', max_length=255, null=True),
        ),
    ]
