# Generated by Django 5.1.3 on 2025-08-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_accordionhtmlpage_sidebar_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordionhtmlpage',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar_links', 'Sidebar Links'), ('sidebar', 'Sidebar')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentpagesidebar',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar_links', 'Sidebar Links'), ('sidebar', 'Sidebar')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='linkpagesidebar',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar_links', 'Sidebar Links'), ('sidebar', 'Sidebar')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sidebarhtmlpage',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar_links', 'Sidebar Links'), ('sidebar', 'Sidebar')], default='sidebar_links', max_length=255, null=True),
        ),
    ]
