# Generated by Django 5.1.3 on 2026-03-31 13:29

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_alter_documentpagesidebar_document_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='announcement_text',
            field=models.CharField(blank=True, help_text='Rolling announcement message', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_announcement',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accordionhtmlpage',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar', 'Sidebar'), ('sidebar_links', 'Sidebar Links')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentpagesidebar',
            name='document_block',
            field=wagtail.fields.StreamField([('document_block', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('link', 'Link'), ('doc', 'Document')], 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('document', 1), ('link', 2), ('display_doc_type', 3), ('open_in_new_tab', 4)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='documentpagesidebar',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar', 'Sidebar'), ('sidebar_links', 'Sidebar Links')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='linkpagesidebar',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar', 'Sidebar'), ('sidebar_links', 'Sidebar Links')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sidebarhtmlpage',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar', 'Sidebar'), ('sidebar_links', 'Sidebar Links')], default='sidebar_links', max_length=255, null=True),
        ),
    ]
