# Generated by Django 5.1.3 on 2026-05-13 08:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_alter_documentpagesidebar_document_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='testimonials',
            field=wagtail.fields.StreamField([('testimonial', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Student Name', 'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Course', 'max_length': 255}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Nepal → Melbourne, AUS', 'label': 'Country Line', 'max_length': 255}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text shown on the image badge, e.g. Master of Professional Accounting', 'label': 'Badge Text', 'max_length': 255}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Quote'}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Photo'}), 6: ('wagtail.blocks.StructBlock', [[('name', 0), ('course', 1), ('country', 2), ('badge', 3), ('quote', 4), ('photo', 5)]], {})}, null=True, verbose_name='Testimonial Cards'),
        ),
    ]
