# Generated by Django 5.1.3 on 2026-05-21 19:06

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_homepage_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='course_tabs',
            field=wagtail.fields.StreamField([('tab', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Text shown on the tab button, e.g. 'IT' or 'Business'", 'label': 'Tab Label', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Unique identifier used for the HTML panel id — no spaces or special characters. e.g. 'it', 'business', 'early-childhood'", 'label': 'Tab Slug', 'max_length': 100}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Master of Information Technology', 'label': 'Course Title', 'max_length': 255}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Card Background Image', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Shown at the top of the modal popup, e.g. 'Postgraduate · Information Technology'", 'label': 'Modal Label', 'max_length': 255}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. 'Postgraduate · 2 years'", 'label': 'Tag / Level & Duration', 'max_length': 255}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'One or two sentences shown in the modal popup.', 'label': 'Short Description'}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. '2 years – 4 Semesters'", 'label': 'Duration', 'max_length': 255}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. 'March, July, November'", 'label': 'Intake Months', 'max_length': 255}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': 'Full URL to the course detail page.', 'label': 'Course Page URL'}), 10: ('wagtail.blocks.StructBlock', [[('title', 2), ('background_image', 3), ('label', 4), ('tag', 5), ('description', 6), ('duration', 7), ('intake', 8), ('url', 9)]], {}), 11: ('wagtail.blocks.StreamBlock', [[('course', 10)]], {'help_text': 'Add the course cards to display under this tab.', 'label': 'Course Cards', 'min_num': 1}), 12: ('wagtail.blocks.StructBlock', [[('tab_label', 0), ('tab_slug', 1), ('courses', 11)]], {})}, help_text="Each item is one tab in the 'Popular courses at Ozford' section. Add tabs for IT, Business, Accounting, Early Childhood, etc. and fill in the course cards for each tab.", null=True, verbose_name='Find Courses — Tabs'),
        ),
        migrations.AlterField(
            model_name='accordionhtmlpage',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar_links', 'Sidebar Links'), ('sidebar', 'Sidebar')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentpagesidebar',
            name='document_block',
            field=wagtail.fields.StreamField([('document_block', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('link', 'Link'), ('doc', 'Document')], 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('document', 1), ('link', 2), ('display_doc_type', 3), ('open_in_new_tab', 4)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='documentpagesidebar',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar_links', 'Sidebar Links'), ('sidebar', 'Sidebar')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='linkpagesidebar',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar_links', 'Sidebar Links'), ('sidebar', 'Sidebar')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sidebarhtmlpage',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar_links', 'Sidebar Links'), ('sidebar', 'Sidebar')], default='sidebar_links', max_length=255, null=True),
        ),
    ]
