# Generated by Django 5.1.3 on 2026-06-22 18:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_homepage_course_tabs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordionhtmlpage',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar', 'Sidebar'), ('sidebar_links', 'Sidebar Links')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentpagesidebar',
            name='document_block',
            field=wagtail.fields.StreamField([('document_block', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('doc', 'Document'), ('link', 'Link')], 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('document', 1), ('link', 2), ('display_doc_type', 3), ('open_in_new_tab', 4)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='documentpagesidebar',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar', 'Sidebar'), ('sidebar_links', 'Sidebar Links')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_carousel',
            field=wagtail.fields.StreamField([('banner_carousel', 7)], blank=True, block_lookup={0: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': '#FFFFFF', 'max_length': 50, 'required': False, 'verbose_name': 'Text Color'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'on_delete': django.db.models.deletion.SET_NULL, 'related_name': '+', 'required': True, 'verbose_name': 'Background Image'}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full Width'), ('fit', 'Fit')]}), 5: ('wagtail.blocks.CharBlock', (), {'default': '#FFFFFF', 'max_length': 50, 'required': False, 'verbose_name': 'Background Color'}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'btn-primary', 'help_text': 'Button class for learn more button. available classes are [btn-parimary (blue), btn-danger (red), btn-success (green), btn-warning (yellow), btn-info (light blue), btn-default (grey)]', 'max_length': 50, 'required': False, 'verbose_name': 'Button Class'}), 7: ('wagtail.blocks.StructBlock', [[('active', 0), ('heading', 1), ('heading_text_color', 2), ('description', 1), ('description_text_color', 2), ('background_image', 3), ('image_width', 4), ('bg_color', 5), ('btn_title', 1), ('btn_link', 1), ('btn_class', 6)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='linkpagesidebar',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar', 'Sidebar'), ('sidebar_links', 'Sidebar Links')], default='sidebar_links', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sidebarhtmlpage',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('sidebar', 'Sidebar'), ('sidebar_links', 'Sidebar Links')], default='sidebar_links', max_length=255, null=True),
        ),
    ]
