# Generated by Django 5.1.3 on 2025-01-16 08:34

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(max_length=255, null=True)),
                ('page_description', wagtail.fields.RichTextField(blank=True, null=True)),
                ('google_map', models.CharField(max_length=255, null=True)),
                ('contact_block', wagtail.fields.StreamField([('contact_blocks', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'null': True}), 2: ('wagtail.blocks.StructBlock', [[('contact_title', 0), ('contact_description', 1)]], {})}, null=True)),
            ],
            options={
                'verbose_name': 'Contact Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
