# Generated by Django 5.1.3 on 2025-01-16 16:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_teampage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teampage',
            name='department_block',
        ),
        migrations.AddField(
            model_name='teampage',
            name='departments',
            field=wagtail.fields.StreamField([('department', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('position', 0), ('profile_image', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('department_title', 0), ('team_members', 4)]], {})}, null=True),
        ),
    ]
