# Generated by Django 5.1.3 on 2025-01-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_teampage_department_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teampage',
            name='departments',
        ),
    ]
