# Generated by Django 5.1.3 on 2025-01-28 06:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_teampage_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampage',
            name='high_school_team',
            field=wagtail.fields.StreamField([('high_school_team', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('position', 0), ('profile_image', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('department_title', 0), ('team_members', 4)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='teampage',
            name='higher_education_team',
            field=wagtail.fields.StreamField([('higher_education_team', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('position', 0), ('profile_image', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('department_title', 0), ('team_members', 4)]], {})}, null=True),
        ),
    ]
