# Generated by Django 5.1.3 on 2025-01-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_teampage_high_school_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampage',
            name='page_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
