# Generated by Django 5.1.3 on 2025-01-28 12:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_contactpage_banner_image_teampage_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampage',
            name='high_school_team',
            field=wagtail.fields.StreamField([('high_school_team', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('position', 1), ('profile_image', 2), ('description', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('department_title', 0), ('team_members', 5)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='teampage',
            name='higher_education_team',
            field=wagtail.fields.StreamField([('higher_education_team', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('position', 1), ('profile_image', 2), ('description', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('department_title', 0), ('team_members', 5)]], {})}, null=True),
        ),
    ]
