# Generated by Django 5.1.3 on 2025-01-28 13:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_teampage_high_school_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampage',
            name='high_school_team',
            field=wagtail.fields.StreamField([('high_school_team', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('position', 1), ('qualification', 1), ('profile_image', 2), ('description', 1)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('department_title', 0), ('team_members', 4)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='teampage',
            name='higher_education_team',
            field=wagtail.fields.StreamField([('higher_education_team', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('position', 1), ('qualification', 1), ('profile_image', 2), ('description', 1)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('department_title', 0), ('team_members', 4)]], {})}, null=True),
        ),
    ]
