# Generated by Django 5.1.3 on 2025-02-24 11:07

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_galleryindexpage'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoriesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(max_length=255, null=True)),
                ('gallery_items', wagtail.fields.StreamField([('video', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enter the URL of the YouTube video', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 3: ('wagtail.blocks.StructBlock', [[('video_url', 0), ('title', 1), ('is_active', 2)]], {})}, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
