# Generated by Django 5.1.3 on 2025-02-24 12:32

import django.db.models.deletion
import tinymce.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_testimonialpage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutindex',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='banner_image'),
        ),
        migrations.AddField(
            model_name='aboutindex',
            name='intro',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutindex',
            name='intro_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='intro_image'),
        ),
        migrations.AddField(
            model_name='aboutindex',
            name='milestones_timeline',
            field=wagtail.fields.StreamField([('milestones_timeline', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('date', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='aboutindex',
            name='page_subtitle',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutindex',
            name='page_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
