# Generated by Django 5.1.3 on 2025-02-24 12:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_aboutindex_banner_image_aboutindex_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutindex',
            name='milestones_timeline',
            field=wagtail.fields.StreamField([('milestones_timeline', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('year', 0), ('description', 1)]], {})}, null=True),
        ),
    ]
