# Generated by Django 5.1.3 on 2025-03-02 05:54

import django.db.models.deletion
import tinymce.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_alter_aboutindex_milestones_timeline'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdorsementPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(max_length=255, null=True)),
                ('page_subtitle', models.CharField(max_length=255, null=True)),
                ('logos', wagtail.fields.StreamField([('logos', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('is_active', 1)]], {})}, null=True)),
                ('body', tinymce.models.HTMLField(blank=True, null=True)),
                ('sidebar_links', wagtail.fields.StreamField([('sidebar_links', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('is_active', 1)]], {})}, null=True)),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='banner_image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
