# Generated by Django 5.1.3 on 2025-03-02 05:58

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0015_edorsementpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialpage',
            name='page_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='edorsementpage',
            name='logos',
            field=wagtail.fields.StreamField([('logos', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('is_active', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='edorsementpage',
            name='page_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='edorsementpage',
            name='sidebar_links',
            field=wagtail.fields.StreamField([('sidebar_links', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('is_active', 1)]], {})}, null=True),
        ),
    ]
