# Generated by Django 5.1.3 on 2025-03-02 06:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_testimonialpage_page_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edorsementpage',
            name='sidebar_links',
            field=wagtail.fields.StreamField([('sidebar_links', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('link_title', 0), ('url', 0), ('open_in_new_tab', 1)]], {})}, null=True),
        ),
    ]
