# Generated by Django 5.1.3 on 2025-04-01 07:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0019_aboutindex_body_aboutindex_body_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edorsementpage',
            name='sidebar_links',
            field=wagtail.fields.StreamField([('sidebar_links', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 500, 'null': True}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('link_title', 0), ('url', 1), ('is_active_link', 2), ('open_in_new_tab', 2)]], {})}, null=True),
        ),
    ]
