# Generated by Django 5.1.3 on 2025-05-26 11:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0021_alter_edorsementpage_sidebar_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialpage',
            name='testimonial',
            field=wagtail.fields.StreamField([('testimonial', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('country', 0), ('course', 0), ('profile_image', 1), ('description', 2), ('display_in_home', 3)]], {})}, null=True),
        ),
    ]
