# Generated by Django 5.1.3 on 2024-12-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
