# Generated by Django 5.1.3 on 2025-01-23 05:54

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesettings_footer_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_note',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='acknowledgement_of_country_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='acknowledgement_of_country_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_primary_links',
            field=wagtail.fields.StreamField([('footer_primary_links', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('link_title', 1), ('url', 1), ('open_in_new_tab', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 4)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_secondary_links',
            field=wagtail.fields.StreamField([('footer_secondary_links', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('link_title', 1), ('url', 1), ('open_in_new_tab', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 4)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_social_media',
            field=wagtail.fields.StreamField([('footer_social_media', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('icon', 1), ('url', 2), ('open_in_new_tab', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('social_media', 5)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_map',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
