# Generated by Django 5.1.3 on 2025-01-23 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_remove_sitesettings_footer_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Global Site Settings'},
        ),
    ]
