# Generated by Django 5.1.3 on 2025-01-23 06:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_alter_sitesettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
