# Generated by Django 5.1.3 on 2025-01-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_alter_sitesettings_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='office_hour',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
