# Generated by Django 5.1.3 on 2025-01-23 08:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_sitesettings_office_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_social_media',
            field=wagtail.fields.StreamField([('footer_social_media', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {'null': True, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('icon', 1), ('icon_svg', 2), ('url', 3), ('open_in_new_tab', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('social_media', 6)]], {})}, null=True),
        ),
    ]
