# Generated by Django 5.1.3 on 2025-01-23 09:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_alter_sitesettings_footer_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_secondary_links',
            field=wagtail.fields.StreamField([('footer_secondary_links', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('link_title', 0), ('url', 0), ('open_in_new_tab', 1)]], {})}, null=True),
        ),
    ]
