# Generated by Django 5.1.3 on 2025-01-23 09:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_alter_sitesettings_footer_secondary_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_primary_links',
            field=wagtail.fields.StreamField([('footer_primary_links', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 1), ('url', 1), ('open_in_new_tab', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 4)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_secondary_links',
            field=wagtail.fields.StreamField([('footer_secondary_links', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('url', 0), ('open_in_new_tab', 1)]], {})}, null=True),
        ),
    ]
