# Generated by Django 5.1.3 on 2025-03-02 08:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_alter_sitesettings_footer_primary_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_social_media',
            field=wagtail.fields.StreamField([('footer_social_media', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.TextBlock', (), {'null': True, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('icon_svg', 1), ('url', 2), ('open_in_new_tab', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('social_media', 5)]], {})}, null=True),
        ),
    ]
