# Generated by Django 5.1.3 on 2025-04-02 14:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_alter_sitesettings_footer_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='affiliations',
            field=wagtail.fields.StreamField([('logos', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('is_active', 1)]], {})}, null=True),
        ),
    ]
