# Generated by Django 5.1.3 on 2025-06-07 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0011_sitesettings_affiliations'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='popup_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Popup End Date'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='popup_is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Popup is Active'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='popup_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Popup Start Date'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_popup_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Site Popup Image'),
        ),
    ]
