# Generated by Django 5.1.3 on 2025-06-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0012_sitesettings_popup_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='popup_height',
            field=models.CharField(blank=True, default='500px', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='popup_width',
            field=models.CharField(blank=True, default='300px', max_length=255, null=True),
        ),
    ]
