# Generated by Django 5.1.3 on 2025-06-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0013_sitesettings_popup_height_sitesettings_popup_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='popup_class',
            field=models.CharField(blank=True, default='500px', max_length=255, null=True, verbose_name='Custom Class'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='popup_height',
            field=models.CharField(blank=True, default='500px', max_length=255, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='popup_width',
            field=models.CharField(blank=True, default='300px', max_length=255, null=True, verbose_name='Width'),
        ),
    ]
