# Generated by Django 5.1.3 on 2025-06-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0014_sitesettings_popup_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='popup_class',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Custom Class'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='popup_is_active',
            field=models.BooleanField(default=True, verbose_name='Popup is Active'),
        ),
    ]
