# Generated by Django 5.1.3 on 2025-06-10 04:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0015_alter_sitesettings_popup_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='acknowledgement_of_country_content',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
