# Generated by Django 5.1.3 on 2026-03-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0016_alter_sitesettings_acknowledgement_of_country_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='rolling_message',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Rolling Message Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rolling_message_is_active',
            field=models.BooleanField(default=False, verbose_name='Show Rolling Message'),
        ),
    ]
