# Generated by Django 5.1.3 on 2025-01-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_feepage_banner_image_feepage_page_intro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feepage',
            old_name='higher_education_fee_block',
            new_name='domestic_higher_education_fee_block',
        ),
    ]
