# Generated by Django 5.1.3 on 2025-01-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0013_rename_higher_education_fee_block_feepage_domestic_higher_education_fee_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feepage',
            old_name='domestic_higher_education_fee_block',
            new_name='international_higher_education_fee_block',
        ),
    ]
