# Generated by Django 5.1.3 on 2025-01-27 11:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0017_alter_feepage_domestic_higher_education_fee_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepage',
            name='international_higher_education_fee_block',
        ),
        migrations.AddField(
            model_name='feepage',
            name='higher_education_fee_block',
            field=wagtail.fields.StreamField([('higher_education_fee_block', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': False, 'max_length': 255, 'null': True}), 1: ('wagtail.blocks.StructBlock', [[('program', 0), ('cricos', 0), ('course_duration', 0), ('international_tution_fee', 0), ('domestic_tuition_fee', 0), ('domestic_fee_help', 0)]], {})}, null=True),
        ),
    ]
